ch_cookie_consent: 
    theme: 'dark' # light, dark
    categories: # Below are the default supported categories
        - 'analytics'
    use_logger: false # Logs user actions to database
    position: 'top' # top, bottom
    simplified: false # When set to true the user can only deny or accept all cookies at once
