<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container23YAsPF\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container23YAsPF/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/Container23YAsPF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\Container23YAsPF\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \Container23YAsPF\srcApp_KernelProdContainer([
    'container.build_hash' => '23YAsPF',
    'container.build_id' => '82b0db3d',
    'container.build_time' => 1594398401,
], __DIR__.\DIRECTORY_SEPARATOR.'Container23YAsPF');
