<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0abpso4\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0abpso4/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/Container0abpso4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\Container0abpso4\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \Container0abpso4\srcApp_KernelProdContainer([
    'container.build_hash' => '0abpso4',
    'container.build_id' => '10924d87',
    'container.build_time' => 1594406064,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0abpso4');
