<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'blog' => [[], ['_controller' => 'App\\Controller\\BlogController::index'], [], [['text', '/blog']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\BlogController::home'], [], [['text', '/']], [], []],
    'hardware' => [[], ['_controller' => 'App\\Controller\\BlogController::hardware'], [], [['text', '/hardware']], [], []],
    'gaming' => [[], ['_controller' => 'App\\Controller\\BlogController::gaming'], [], [['text', '/gaming']], [], []],
    'blog_create' => [[], ['_controller' => 'App\\Controller\\BlogController::create'], [], [['text', '/blog/new']], [], []],
    'blog_edit' => [['id'], ['_controller' => 'App\\Controller\\BlogController::create'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/blog']], [], []],
    'blog_show' => [['id'], ['_controller' => 'App\\Controller\\BlogController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/blog']], [], []],
    'privacy-statement' => [[], ['_controller' => 'App\\Controller\\BlogController::private'], [], [['text', '/privacy-statement']], [], []],
    'security_registration' => [[], ['_controller' => 'App\\Controller\\SecurityController::registration'], [], [['text', '/inscription']], [], []],
    'security_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/connexion']], [], []],
    'security_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/deconnexion']], [], []],
    'ch_cookie_consent.show' => [[], ['_controller' => 'ConnectHolland\\CookieConsentBundle\\Controller\\CookieConsentController::show'], [], [['text', '/cookie_consent']], [], []],
    'ch_cookie_consent.show_if_cookie_consent_not_set' => [[], ['_controller' => 'ConnectHolland\\CookieConsentBundle\\Controller\\CookieConsentController::showIfCookieConsentNotSet'], [], [['text', '/cookie_consent_alt']], [], []],
    'easyadmin' => [[], ['_controller' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Controller\\EasyAdminController::indexAction'], [], [['text', '/admin/']], [], []],
];
