<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKBXIATP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKBXIATP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKBXIATP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKBXIATP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKBXIATP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KBXIATP',
    'container.build_id' => 'd13284d2',
    'container.build_time' => 1594399343,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKBXIATP');
