<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.0c796a0d.js',
                '/build/2.85610713.js',
                '/build/app.a6f6d55e.js',
            ],
            'css' => [
                '/build/2.e6b28ac1.css',
                '/build/app.e349f57d.css',
            ],
        ],
        'main' => [
            'js' => [
                '/build/runtime.0c796a0d.js',
                '/build/0.e09fa8bf.js',
                '/build/main.fce4cc0e.js',
            ],
        ],
        'bootstrapjs' => [
            'js' => [
                '/build/runtime.0c796a0d.js',
                '/build/0.e09fa8bf.js',
                '/build/1.3751bb7c.js',
                '/build/bootstrapjs.cb10e863.js',
            ],
        ],
        'cookies' => [
            'js' => [
                '/build/runtime.0c796a0d.js',
                '/build/1.3751bb7c.js',
                '/build/cookies.1db45dae.js',
            ],
        ],
        'anim0' => [
            'js' => [
                '/build/runtime.0c796a0d.js',
                '/build/0.e09fa8bf.js',
                '/build/anim0.7b4f537b.js',
            ],
        ],
        'anim1' => [
            'js' => [
                '/build/runtime.0c796a0d.js',
                '/build/0.e09fa8bf.js',
                '/build/anim1.75ef68ef.js',
            ],
        ],
        'home' => [
            'js' => [
                '/build/runtime.0c796a0d.js',
            ],
            'css' => [
                '/build/home.41eaa2d2.css',
            ],
        ],
        'test' => [
            'js' => [
                '/build/runtime.0c796a0d.js',
            ],
            'css' => [
                '/build/test.47ed2625.css',
            ],
        ],
        'cookiesscss' => [
            'js' => [
                '/build/runtime.0c796a0d.js',
            ],
            'css' => [
                '/build/cookiesscss.1e0a14f0.css',
            ],
        ],
        'style' => [
            'js' => [
                '/build/runtime.0c796a0d.js',
            ],
            'css' => [
                '/build/style.33c4d76a.css',
            ],
        ],
    ],
],

]];
