<?php

namespace Proxies\__CG__\ConnectHolland\CookieConsentBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CookieConsentLog extends \ConnectHolland\CookieConsentBundle\Entity\CookieConsentLog implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'ipAddress', 'cookieConsentKey', 'cookieName', 'cookieValue', 'timestamp'];
        }

        return ['__isInitialized__', 'id', 'ipAddress', 'cookieConsentKey', 'cookieName', 'cookieValue', 'timestamp'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CookieConsentLog $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIpAddress(string $ipAddress): \ConnectHolland\CookieConsentBundle\Entity\CookieConsentLog
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIpAddress', [$ipAddress]);

        return parent::setIpAddress($ipAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getIpAddress(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIpAddress', []);

        return parent::getIpAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCookieConsentKey(string $cookieConsentKey): \ConnectHolland\CookieConsentBundle\Entity\CookieConsentLog
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCookieConsentKey', [$cookieConsentKey]);

        return parent::setCookieConsentKey($cookieConsentKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getCookieConsentKey(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCookieConsentKey', []);

        return parent::getCookieConsentKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setCookieName(string $cookieName): \ConnectHolland\CookieConsentBundle\Entity\CookieConsentLog
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCookieName', [$cookieName]);

        return parent::setCookieName($cookieName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCookieName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCookieName', []);

        return parent::getCookieName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCookieValue(string $cookieValue): \ConnectHolland\CookieConsentBundle\Entity\CookieConsentLog
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCookieValue', [$cookieValue]);

        return parent::setCookieValue($cookieValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getCookieValue(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCookieValue', []);

        return parent::getCookieValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimestamp(\DateTime $timestamp): \ConnectHolland\CookieConsentBundle\Entity\CookieConsentLog
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimestamp', [$timestamp]);

        return parent::setTimestamp($timestamp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimestamp(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimestamp', []);

        return parent::getTimestamp();
    }

}
